config/routes.rb
Railstest::Application.routes.draw do
  get "users/show"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"} 
  
  resources  :users, :only => [:vote] do
    member { post :vote }
  end

  resources :products do
    resources :images
  end

  root :to => "products#index"
 
  get '/users/:id' => 'users#show', :as => :user
  get '/users/' => 'users#index', :as => :users
  get '/my_products/' => 'products#user_index', :as => :user_products
  get '/my_products/:id' => 'products#user_show', :as => :user_product
  

  

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
  has_attached_file :file,
  					:styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :images, dependent: :destroy
	belongs_to :user

	validates :name, :presence => true, :uniqueness => true
	validates :price, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  #allows for user messages
  include Mailboxer::Models::Messageable
  acts_as_messageable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # allows for user ratings
  has_reputation :votes, source: :user, aggregated_by: :average

  has_many :products, dependent: :destroy

  def name
  	return [first_name, last_name].join(' ')
  end

  def mailboxer_email(object)
    email
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_filter :authenticate_user!, except: [:show]
	def create
		@product = Product.find(params[:product_id])
		@image = @product.images.create(params[:image].permit(:title,:location,:file))
		redirect_to user_product_path(@product)
	end
	def destroy
	    @product = Product.find(params[:product_id])
	    @image = @product.images.find(params[:id])
	    @image.destroy
	    redirect_to user_product_path(@product)
  	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def user_index
    @user = User.find(current_user.id)
    @products = @user.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def user_show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    #add redirect if product doesn't belong to current user
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to user_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to user_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :content, :description, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!, only: [:index, :show]
  
  def index
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def products
    @products = User.products
  end

  def vote
    notice = "Thanks for voting"
    @user = User.find(params[:id])

  	if @user.id == current_user.id
      notice = "You cannot vote for yourself"
    else
      value = params[:type].to_i
      begin
    	   @user.add_evaluation(:votes, value, current_user)
    	rescue ActiveRecord::RecordInvalid
          notice = "You have already voted"
      end
    end
    redirect_to :back, notice: notice
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_for([@product, @product.images.build], :html => { :multipart => true }) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <%= f.file_field :file %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/images/_image.html.erb
<p>
	<strong>Title:</strong>
	<%= image.title %>
</p>

<%= image_tag image.file.url %>
<% if user_signed_in? %>
	<p>
	  <%= link_to 'Destroy Image', [image.product, image],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railstest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="content">
	
	<%= link_to "Home", root_path %> | 
	<% if user_signed_in? %>
	  <%= link_to "Edit profile", edit_user_registration_path %> |
	  <%= link_to 'See User List', users_path %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete %><br><br>
	  Logged in as <strong><%= current_user.email %></strong>.
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path %> |
	  <%= link_to "Login", new_user_session_path %>
	<% end %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %><br><br><br>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, value: number_with_precision(f.object.price, precision: 2) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', user_products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.user_id %></td>
        <td><%= link_to 'Show', product %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'See Your Products', user_products_path %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @product.user.first_name %>
  <%= @product.user.last_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<h2>Images</h2>
<%= render @product.images  %>

<% if (user_signed_in?) && (current_user.id == @product.user.id) %>
	<h2>Add an image:</h2>
	<%= render "images/form" %>
	<%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', products_path %>

app/views/products/user_index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user.products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.user_id %></td>
        <td><%= link_to 'Show', user_product_path(product.id) %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/user_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @product.user.first_name %>
  <%= @product.user.last_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<h2>Images</h2>
<%= render @product.images  %>


<h2>Add an image:</h2>
<%= render "images/form" %>
<%= link_to 'Edit', edit_product_path(@product) %> |

<%= link_to 'Back', user_products_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Ranking</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.reputation_for(:votes) %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<h1>Users#show</h1>
<%= @user.first_name %>
<%= @user.last_name %>
<%= @user.email %>
<br>
<p>Current user score: <%= @user.reputation_for(:votes) %></p>
<p>Vote for this user: 
<%= link_to "1", vote_user_path(@user, type: "1"), method: "post" %> | 
<%= link_to "2", vote_user_path(@user, type: "2"), method: "post" %> | 
<%= link_to "3", vote_user_path(@user, type: "3"), method: "post" %> | 
<%= link_to "4", vote_user_path(@user, type: "4"), method: "post" %> | 
<%= link_to "5", vote_user_path(@user, type: "5"), method: "post" %>
</p>